CREATE TABLE public.planetarysystemstable (
                                              id INT8,
                                              pl_name VARCHAR(50),
                                              hostname VARCHAR(50),
                                              pl_letter VARCHAR(1),
                                              hd_name VARCHAR(25),
                                              hip_name VARCHAR(25),
                                              tic_id VARCHAR(25),
                                              gaia_id VARCHAR(50),
                                              sy_snum INT4,
                                              sy_pnum INT4,
                                              sy_mnum INT4,
                                              cb_flag INT2,
                                              discoverymethod VARCHAR(50),
                                              disc_year INT4,
                                              disc_refname VARCHAR(255),
                                              disc_pubdate VARCHAR(50),
                                              disc_locale VARCHAR(50),
                                              disc_facility VARCHAR(50),
                                              disc_telescope VARCHAR(125),
                                              disc_instrument VARCHAR(50),
                                              rv_flag INT2,
                                              pul_flag INT2,
                                              ptv_flag INT2,
                                              tran_flag INT2,
                                              ast_flag INT2,
                                              obm_flag INT2,
                                              micro_flag INT2,
                                              etv_flag INT2,
                                              ima_flag INT2,
                                              dkin_flag INT2,
                                              pl_controv_flag INT2,
                                              pl_orbper FLOAT8,
                                              pl_orbpererr1 FLOAT8,
                                              pl_orbpererr2 FLOAT8,
                                              pl_orbperlim INT4,
                                              pl_orbper_reflink VARCHAR(255),
                                              pl_orbsmax FLOAT8,
                                              pl_orbsmaxerr1 FLOAT8,
                                              pl_orbsmaxerr2 FLOAT8,
                                              pl_orbsmaxlim INT4,
                                              pl_orbsmax_reflink VARCHAR(255),
                                              pl_rade FLOAT8,
                                              pl_radeerr1 FLOAT8,
                                              pl_radeerr2 FLOAT8,
                                              pl_radelim INT4,
                                              pl_rade_reflink VARCHAR(255),
                                              pl_radj FLOAT8,
                                              pl_radjerr1 FLOAT8,
                                              pl_radjerr2 FLOAT8,
                                              pl_radjlim INT4,
                                              pl_radj_reflink VARCHAR(255),
                                              pl_bmasse FLOAT8,
                                              pl_bmasseerr1 FLOAT8,
                                              pl_bmasseerr2 FLOAT8,
                                              pl_bmasselim INT4,
                                              pl_bmasse_reflink VARCHAR(255),
                                              pl_bmassj FLOAT8,
                                              pl_bmassjerr1 FLOAT8,
                                              pl_bmassjerr2 FLOAT8,
                                              pl_bmassjlim INT4,
                                              pl_bmassj_reflink VARCHAR(255),
                                              pl_bmassprov VARCHAR(25),
                                              pl_dens FLOAT8,
                                              pl_denserr1 FLOAT8,
                                              pl_denserr2 FLOAT8,
                                              pl_denslim INT4,
                                              pl_dens_reflink VARCHAR(255),
                                              pl_orbeccen FLOAT8,
                                              pl_orbeccenerr1 FLOAT8,
                                              pl_orbeccenerr2 FLOAT8,
                                              pl_orbeccenlim INT4,
                                              pl_orbeccen_reflink VARCHAR(255),
                                              pl_insol FLOAT8,
                                              pl_insolerr1 FLOAT8,
                                              pl_insolerr2 FLOAT8,
                                              pl_insollim INT4,
                                              pl_insol_reflink VARCHAR(255),
                                              pl_eqt FLOAT8,
                                              pl_eqterr1 FLOAT8,
                                              pl_eqterr2 FLOAT8,
                                              pl_eqtlim INT4,
                                              pl_eqt_reflink VARCHAR(255),
                                              pl_orbincl FLOAT8,
                                              pl_orbinclerr1 FLOAT8,
                                              pl_orbinclerr2 FLOAT8,
                                              pl_orbincllim INT4,
                                              pl_orbincl_reflink VARCHAR(255),
                                              pl_tranmid FLOAT8,
                                              pl_tranmiderr1 FLOAT8,
                                              pl_tranmiderr2 FLOAT8,
                                              pl_tranmidlim INT4,
                                              pl_tranmid_systemref VARCHAR(10),
                                              pl_tranmid_reflink VARCHAR(255),
                                              ttv_flag INT2,
                                              pl_imppar FLOAT8,
                                              pl_impparerr1 FLOAT8,
                                              pl_impparerr2 FLOAT8,
                                              pl_impparlim INT4,
                                              pl_imppar_reflink VARCHAR(255),
                                              pl_trandep FLOAT8,
                                              pl_trandeperr1 FLOAT8,
                                              pl_trandeperr2 FLOAT8,
                                              pl_trandeplim INT4,
                                              pl_trandep_reflink VARCHAR(255),
                                              pl_trandur FLOAT8,
                                              pl_trandurerr1 FLOAT8,
                                              pl_trandurerr2 FLOAT8,
                                              pl_trandurlim INT4,
                                              pl_trandur_reflink VARCHAR(255),
                                              pl_ratdor FLOAT8,
                                              pl_ratdorerr1 FLOAT8,
                                              pl_ratdorerr2 FLOAT8,
                                              pl_ratdorlim INT4,
                                              pl_ratdor_reflink VARCHAR(255),
                                              pl_ratror FLOAT8,
                                              pl_ratrorerr1 FLOAT8,
                                              pl_ratrorerr2 FLOAT8,
                                              pl_ratrorlim INT4,
                                              pl_ratror_reflink VARCHAR(255),
                                              pl_occdep FLOAT8,
                                              pl_occdeperr1 FLOAT8,
                                              pl_occdeperr2 FLOAT8,
                                              pl_occdeplim INT4,
                                              pl_occdep_reflink VARCHAR(255),
                                              pl_orbtper FLOAT8,
                                              pl_orbtpererr1 FLOAT8,
                                              pl_orbtpererr2 FLOAT8,
                                              pl_orbtperlim INT4,
                                              pl_orbtper_systemref VARCHAR(10),
                                              pl_orbtper_reflink VARCHAR(255),
                                              pl_orblper FLOAT8,
                                              pl_orblpererr1 FLOAT8,
                                              pl_orblpererr2 FLOAT8,
                                              pl_orblperlim INT4,
                                              pl_orblper_reflink VARCHAR(255),
                                              pl_rvamp FLOAT8,
                                              pl_rvamperr1 FLOAT8,
                                              pl_rvamperr2 FLOAT8,
                                              pl_rvamplim INT4,
                                              pl_rvamp_reflink VARCHAR(255),
                                              pl_projobliq FLOAT8,
                                              pl_projobliqerr1 FLOAT8,
                                              pl_projobliqerr2 FLOAT8,
                                              pl_projobliqlim INT4,
                                              pl_projobliq_reflink VARCHAR(255),
                                              pl_trueobliq FLOAT8,
                                              pl_trueobliqerr1 FLOAT8,
                                              pl_trueobliqerr2 FLOAT8,
                                              pl_trueobliqlim INT4,
                                              pl_trueobliq_reflink VARCHAR(255),
                                              st_spectype VARCHAR(25),
                                              st_spectype_reflink VARCHAR(255),
                                              st_teff FLOAT8,
                                              st_tefferr1 FLOAT8,
                                              st_tefferr2 FLOAT8,
                                              st_tefflim INT4,
                                              st_teff_reflink VARCHAR(255),
                                              st_rad FLOAT8,
                                              st_raderr1 FLOAT8,
                                              st_raderr2 FLOAT8,
                                              st_radlim INT4,
                                              st_rad_reflink VARCHAR(255),
                                              st_mass FLOAT8,
                                              st_masserr1 FLOAT8,
                                              st_masserr2 FLOAT8,
                                              st_masslim INT4,
                                              st_mass_reflink VARCHAR(255),
                                              st_met FLOAT8,
                                              st_meterr1 FLOAT8,
                                              st_meterr2 FLOAT8,
                                              st_metlim INT4,
                                              st_met_reflink VARCHAR(255),
                                              st_metratio VARCHAR(10),
                                              st_lum FLOAT8,
                                              st_lumerr1 FLOAT8,
                                              st_lumerr2 FLOAT8,
                                              st_lumlim INT4,
                                              st_lum_reflink VARCHAR(255),
                                              st_logg FLOAT8,
                                              st_loggerr1 FLOAT8,
                                              st_loggerr2 FLOAT8,
                                              st_logglim INT4,
                                              st_logg_reflink VARCHAR(255),
                                              st_age FLOAT8,
                                              st_ageerr1 FLOAT8,
                                              st_ageerr2 FLOAT8,
                                              st_agelim INT4,
                                              st_age_reflink VARCHAR(255),
                                              st_dens FLOAT8,
                                              st_denserr1 FLOAT8,
                                              st_denserr2 FLOAT8,
                                              st_denslim INT4,
                                              st_dens_reflink VARCHAR(255),
                                              st_vsin FLOAT8,
                                              st_vsinerr1 FLOAT8,
                                              st_vsinerr2 FLOAT8,
                                              st_vsinlim INT4,
                                              st_vsin_reflink VARCHAR(255),
                                              st_rotp FLOAT8,
                                              st_rotperr1 FLOAT8,
                                              st_rotperr2 FLOAT8,
                                              st_rotplim INT4,
                                              st_rotp_reflink VARCHAR(255),
                                              st_radv FLOAT8,
                                              st_radverr1 FLOAT8,
                                              st_radverr2 FLOAT8,
                                              st_radvlim INT4,
                                              st_radv_reflink VARCHAR(255),
                                              rastr VARCHAR(15),
                                              ra FLOAT8,
                                              decstr VARCHAR(15),
                                              dec FLOAT8,
                                              raerr1 FLOAT8,
                                              raerr2 FLOAT8,
                                              decerr1 FLOAT8,
                                              decerr2 FLOAT8,
                                              glat FLOAT8,
                                              glaterr1 FLOAT8,
                                              glaterr2 FLOAT8,
                                              glon FLOAT8,
                                              glonerr1 FLOAT8,
                                              glonerr2 FLOAT8,
                                              elat FLOAT8,
                                              elaterr1 FLOAT8,
                                              elaterr2 FLOAT8,
                                              elon FLOAT8,
                                              elonerr1 FLOAT8,
                                              elonerr2 FLOAT8,
                                              ra_reflink VARCHAR(255),
                                              sy_pm FLOAT8,
                                              sy_pmerr1 FLOAT8,
                                              sy_pmerr2 FLOAT8,
                                              sy_pm_reflink VARCHAR(255),
                                              sy_pmra FLOAT8,
                                              sy_pmraerr1 FLOAT8,
                                              sy_pmraerr2 FLOAT8,
                                              sy_pmra_reflink VARCHAR(255),
                                              sy_pmdec FLOAT8,
                                              sy_pmdecerr1 FLOAT8,
                                              sy_pmdecerr2 FLOAT8,
                                              sy_pmdec_reflink VARCHAR(255),
                                              sy_dist FLOAT8,
                                              sy_disterr1 FLOAT8,
                                              sy_disterr2 FLOAT8,
                                              sy_dist_reflink VARCHAR(255),
                                              sy_plx FLOAT8,
                                              sy_plxerr1 FLOAT8,
                                              sy_plxerr2 FLOAT8,
                                              sy_plx_reflink VARCHAR(255),
                                              sy_bmag FLOAT8,
                                              sy_bmagerr1 FLOAT8,
                                              sy_bmagerr2 FLOAT8,
                                              sy_bmag_reflink VARCHAR(255),
                                              sy_vmag FLOAT8,
                                              sy_vmagerr1 FLOAT8,
                                              sy_vmagerr2 FLOAT8,
                                              sy_vmag_reflink VARCHAR(255),
                                              sy_jmag FLOAT8,
                                              sy_jmagerr1 FLOAT8,
                                              sy_jmagerr2 FLOAT8,
                                              sy_jmag_reflink VARCHAR(255),
                                              sy_hmag FLOAT8,
                                              sy_hmagerr1 FLOAT8,
                                              sy_hmagerr2 FLOAT8,
                                              sy_hmag_reflink VARCHAR(255),
                                              sy_kmag FLOAT8,
                                              sy_kmagerr1 FLOAT8,
                                              sy_kmagerr2 FLOAT8,
                                              sy_kmag_reflink VARCHAR(255),
                                              sy_umag FLOAT8,
                                              sy_umagerr1 FLOAT8,
                                              sy_umagerr2 FLOAT8,
                                              sy_umag_reflink VARCHAR(255),
                                              sy_gmag FLOAT8,
                                              sy_gmagerr1 FLOAT8,
                                              sy_gmagerr2 FLOAT8,
                                              sy_gmag_reflink VARCHAR(255),
                                              sy_rmag FLOAT8,
                                              sy_rmagerr1 FLOAT8,
                                              sy_rmagerr2 FLOAT8,
                                              sy_rmag_reflink VARCHAR(255),
                                              sy_imag FLOAT8,
                                              sy_imagerr1 FLOAT8,
                                              sy_imagerr2 FLOAT8,
                                              sy_imag_reflink VARCHAR(255),
                                              sy_zmag FLOAT8,
                                              sy_zmagerr1 FLOAT8,
                                              sy_zmagerr2 FLOAT8,
                                              sy_zmag_reflink VARCHAR(255),
                                              sy_w1mag FLOAT8,
                                              sy_w1magerr1 FLOAT8,
                                              sy_w1magerr2 FLOAT8,
                                              sy_w1mag_reflink VARCHAR(255),
                                              sy_w2mag FLOAT8,
                                              sy_w2magerr1 FLOAT8,
                                              sy_w2magerr2 FLOAT8,
                                              sy_w2mag_reflink VARCHAR(255),
                                              sy_w3mag FLOAT8,
                                              sy_w3magerr1 FLOAT8,
                                              sy_w3magerr2 FLOAT8,
                                              sy_w3mag_reflink VARCHAR(255),
                                              sy_w4mag FLOAT8,
                                              sy_w4magerr1 FLOAT8,
                                              sy_w4magerr2 FLOAT8,
                                              sy_w4mag_reflink VARCHAR(255),
                                              sy_gaiamag FLOAT8,
                                              sy_gaiamagerr1 FLOAT8,
                                              sy_gaiamagerr2 FLOAT8,
                                              sy_gaiamag_reflink VARCHAR(255),
                                              sy_icmag FLOAT8,
                                              sy_icmagerr1 FLOAT8,
                                              sy_icmagerr2 FLOAT8,
                                              sy_icmag_reflink VARCHAR(255),
                                              sy_tmag FLOAT8,
                                              sy_tmagerr1 FLOAT8,
                                              sy_tmagerr2 FLOAT8,
                                              sy_tmag_reflink VARCHAR(255),
                                              sy_kepmag FLOAT8,
                                              sy_kepmagerr1 FLOAT8,
                                              sy_kepmagerr2 FLOAT8,
                                              sy_kepmag_reflink VARCHAR(255),
                                              pl_nnotes INT4,
                                              st_nphot INT4,
                                              st_nrvc INT4,
                                              st_nspec INT4,
                                              pl_nespec INT4,
                                              pl_ntranspec INT4,
                                              PRIMARY KEY (id)
);

COPY public.planetarysystemstable (
                                   id,
                                   pl_name,
                                   hostname,
                                   pl_letter,
                                   hd_name,
                                   hip_name,
                                   tic_id,
                                   gaia_id,
                                   sy_snum,
                                   sy_pnum,
                                   sy_mnum,
                                   cb_flag,
                                   discoverymethod,
                                   disc_year,
                                   disc_refname,
                                   disc_pubdate,
                                   disc_locale,
                                   disc_facility,
                                   disc_telescope,
                                   disc_instrument,
                                   rv_flag,
                                   pul_flag,
                                   ptv_flag,
                                   tran_flag,
                                   ast_flag,
                                   obm_flag,
                                   micro_flag,
                                   etv_flag,
                                   ima_flag,
                                   dkin_flag,
                                   pl_controv_flag,
                                   pl_orbper,
                                   pl_orbpererr1,
                                   pl_orbpererr2,
                                   pl_orbperlim,
                                   pl_orbper_reflink,
                                   pl_orbsmax,
                                   pl_orbsmaxerr1,
                                   pl_orbsmaxerr2,
                                   pl_orbsmaxlim,
                                   pl_orbsmax_reflink,
                                   pl_rade,
                                   pl_radeerr1,
                                   pl_radeerr2,
                                   pl_radelim,
                                   pl_rade_reflink,
                                   pl_radj,
                                   pl_radjerr1,
                                   pl_radjerr2,
                                   pl_radjlim,
                                   pl_radj_reflink,
                                   pl_bmasse,
                                   pl_bmasseerr1,
                                   pl_bmasseerr2,
                                   pl_bmasselim,
                                   pl_bmasse_reflink,
                                   pl_bmassj,
                                   pl_bmassjerr1,
                                   pl_bmassjerr2,
                                   pl_bmassjlim,
                                   pl_bmassj_reflink,
                                   pl_bmassprov,
                                   pl_dens,
                                   pl_denserr1,
                                   pl_denserr2,
                                   pl_denslim,
                                   pl_dens_reflink,
                                   pl_orbeccen,
                                   pl_orbeccenerr1,
                                   pl_orbeccenerr2,
                                   pl_orbeccenlim,
                                   pl_orbeccen_reflink,
                                   pl_insol,
                                   pl_insolerr1,
                                   pl_insolerr2,
                                   pl_insollim,
                                   pl_insol_reflink,
                                   pl_eqt,
                                   pl_eqterr1,
                                   pl_eqterr2,
                                   pl_eqtlim,
                                   pl_eqt_reflink,
                                   pl_orbincl,
                                   pl_orbinclerr1,
                                   pl_orbinclerr2,
                                   pl_orbincllim,
                                   pl_orbincl_reflink,
                                   pl_tranmid,
                                   pl_tranmiderr1,
                                   pl_tranmiderr2,
                                   pl_tranmidlim,
                                   pl_tranmid_systemref,
                                   pl_tranmid_reflink,
                                   ttv_flag,
                                   pl_imppar,
                                   pl_impparerr1,
                                   pl_impparerr2,
                                   pl_impparlim,
                                   pl_imppar_reflink,
                                   pl_trandep,
                                   pl_trandeperr1,
                                   pl_trandeperr2,
                                   pl_trandeplim,
                                   pl_trandep_reflink,
                                   pl_trandur,
                                   pl_trandurerr1,
                                   pl_trandurerr2,
                                   pl_trandurlim,
                                   pl_trandur_reflink,
                                   pl_ratdor,
                                   pl_ratdorerr1,
                                   pl_ratdorerr2,
                                   pl_ratdorlim,
                                   pl_ratdor_reflink,
                                   pl_ratror,
                                   pl_ratrorerr1,
                                   pl_ratrorerr2,
                                   pl_ratrorlim,
                                   pl_ratror_reflink,
                                   pl_occdep,
                                   pl_occdeperr1,
                                   pl_occdeperr2,
                                   pl_occdeplim,
                                   pl_occdep_reflink,
                                   pl_orbtper,
                                   pl_orbtpererr1,
                                   pl_orbtpererr2,
                                   pl_orbtperlim,
                                   pl_orbtper_systemref,
                                   pl_orbtper_reflink,
                                   pl_orblper,
                                   pl_orblpererr1,
                                   pl_orblpererr2,
                                   pl_orblperlim,
                                   pl_orblper_reflink,
                                   pl_rvamp,
                                   pl_rvamperr1,
                                   pl_rvamperr2,
                                   pl_rvamplim,
                                   pl_rvamp_reflink,
                                   pl_projobliq,
                                   pl_projobliqerr1,
                                   pl_projobliqerr2,
                                   pl_projobliqlim,
                                   pl_projobliq_reflink,
                                   pl_trueobliq,
                                   pl_trueobliqerr1,
                                   pl_trueobliqerr2,
                                   pl_trueobliqlim,
                                   pl_trueobliq_reflink,
                                   st_spectype,
                                   st_spectype_reflink,
                                   st_teff,
                                   st_tefferr1,
                                   st_tefferr2,
                                   st_tefflim,
                                   st_teff_reflink,
                                   st_rad,
                                   st_raderr1,
                                   st_raderr2,
                                   st_radlim,
                                   st_rad_reflink,
                                   st_mass,
                                   st_masserr1,
                                   st_masserr2,
                                   st_masslim,
                                   st_mass_reflink,
                                   st_met,
                                   st_meterr1,
                                   st_meterr2,
                                   st_metlim,
                                   st_met_reflink,
                                   st_metratio,
                                   st_lum,
                                   st_lumerr1,
                                   st_lumerr2,
                                   st_lumlim,
                                   st_lum_reflink,
                                   st_logg,
                                   st_loggerr1,
                                   st_loggerr2,
                                   st_logglim,
                                   st_logg_reflink,
                                   st_age,
                                   st_ageerr1,
                                   st_ageerr2,
                                   st_agelim,
                                   st_age_reflink,
                                   st_dens,
                                   st_denserr1,
                                   st_denserr2,
                                   st_denslim,
                                   st_dens_reflink,
                                   st_vsin,
                                   st_vsinerr1,
                                   st_vsinerr2,
                                   st_vsinlim,
                                   st_vsin_reflink,
                                   st_rotp,
                                   st_rotperr1,
                                   st_rotperr2,
                                   st_rotplim,
                                   st_rotp_reflink,
                                   st_radv,
                                   st_radverr1,
                                   st_radverr2,
                                   st_radvlim,
                                   st_radv_reflink,
                                   rastr,
                                   ra,
                                   decstr,
                                   dec,
                                   raerr1,
                                   raerr2,
                                   decerr1,
                                   decerr2,
                                   glat,
                                   glaterr1,
                                   glaterr2,
                                   glon,
                                   glonerr1,
                                   glonerr2,
                                   elat,
                                   elaterr1,
                                   elaterr2,
                                   elon,
                                   elonerr1,
                                   elonerr2,
                                   ra_reflink,
                                   sy_pm,
                                   sy_pmerr1,
                                   sy_pmerr2,
                                   sy_pm_reflink,
                                   sy_pmra,
                                   sy_pmraerr1,
                                   sy_pmraerr2,
                                   sy_pmra_reflink,
                                   sy_pmdec,
                                   sy_pmdecerr1,
                                   sy_pmdecerr2,
                                   sy_pmdec_reflink,
                                   sy_dist,
                                   sy_disterr1,
                                   sy_disterr2,
                                   sy_dist_reflink,
                                   sy_plx,
                                   sy_plxerr1,
                                   sy_plxerr2,
                                   sy_plx_reflink,
                                   sy_bmag,
                                   sy_bmagerr1,
                                   sy_bmagerr2,
                                   sy_bmag_reflink,
                                   sy_vmag,
                                   sy_vmagerr1,
                                   sy_vmagerr2,
                                   sy_vmag_reflink,
                                   sy_jmag,
                                   sy_jmagerr1,
                                   sy_jmagerr2,
                                   sy_jmag_reflink,
                                   sy_hmag,
                                   sy_hmagerr1,
                                   sy_hmagerr2,
                                   sy_hmag_reflink,
                                   sy_kmag,
                                   sy_kmagerr1,
                                   sy_kmagerr2,
                                   sy_kmag_reflink,
                                   sy_umag,
                                   sy_umagerr1,
                                   sy_umagerr2,
                                   sy_umag_reflink,
                                   sy_gmag,
                                   sy_gmagerr1,
                                   sy_gmagerr2,
                                   sy_gmag_reflink,
                                   sy_rmag,
                                   sy_rmagerr1,
                                   sy_rmagerr2,
                                   sy_rmag_reflink,
                                   sy_imag,
                                   sy_imagerr1,
                                   sy_imagerr2,
                                   sy_imag_reflink,
                                   sy_zmag,
                                   sy_zmagerr1,
                                   sy_zmagerr2,
                                   sy_zmag_reflink,
                                   sy_w1mag,
                                   sy_w1magerr1,
                                   sy_w1magerr2,
                                   sy_w1mag_reflink,
                                   sy_w2mag,
                                   sy_w2magerr1,
                                   sy_w2magerr2,
                                   sy_w2mag_reflink,
                                   sy_w3mag,
                                   sy_w3magerr1,
                                   sy_w3magerr2,
                                   sy_w3mag_reflink,
                                   sy_w4mag,
                                   sy_w4magerr1,
                                   sy_w4magerr2,
                                   sy_w4mag_reflink,
                                   sy_gaiamag,
                                   sy_gaiamagerr1,
                                   sy_gaiamagerr2,
                                   sy_gaiamag_reflink,
                                   sy_icmag,
                                   sy_icmagerr1,
                                   sy_icmagerr2,
                                   sy_icmag_reflink,
                                   sy_tmag,
                                   sy_tmagerr1,
                                   sy_tmagerr2,
                                   sy_tmag_reflink,
                                   sy_kepmag,
                                   sy_kepmagerr1,
                                   sy_kepmagerr2,
                                   sy_kepmag_reflink,
                                   pl_nnotes,
                                   st_nphot,
                                   st_nrvc,
                                   st_nspec,
                                   pl_nespec,
                                   pl_ntranspec
    )
    FROM 'Y:\planets.csv'
    DELIMITER ','
    CSV HEADER;


