# Java Maven CircleCI 2.1 configuration file
#
# Reference https://circleci.com/docs/2.0/language-java-maven/
#
version: 2.1

orbs:
  maven: circleci/maven@0.0.12

workflows:
  maven_test:
    jobs:
      - maven/test # checkout, build, test, and upload test results
